---
- name: restart Elasticsearch
  become: true
  service:
    name: elasticsearch
    state: restarted
  when: ansible_facts.pkg_mgr == "yum"
- name: restart Elasticsearch
  service:
    name: elasticsearch
    state: restarted
  when: ansible_facts.pkg_mgr == "deb"