---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: instance-1
    image: docker.io/pycontribs/centos:7
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    published_ports:
      - 0.0.0.0:5003:5003/udp
      - 0.0.0.0:5003:5003/tcp
    pre_build_image: true
  - name: instance-2
    image: docker.io/pycontribs/ubuntu:latest
    privileged: True
    published_ports:
      - 0.0.0.0:5004:5004/udp
      - 0.0.0.0:5004:5004/tcp
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  options:
    vvv: true
    diff: true
verifier:
  name: ansible