---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: elastic-centos
    image: docker.io/pycontribs/centos:7
    command: /sbin/init
    privileged: True
    # volumes:
      # - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # exposed_ports:
    #   - 9000/tcp
    # published_ports:
    #   - 0.0.0.0:9000:9000/tcp
    network:
      - elk-centos
    pre_build_image: true
  - name: elastic-ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    # exposed_ports:
    #   - 9100/tcp
    # published_ports:
    #   - 0.0.0.0:9100:9100/tcp
    network:
      - elk-ubuntu
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    host_vars:
      instance-1:
        elk_id: 0
      instance-2:
        elk_id: 1
verifier:
  name: ansible