---
- name: Add JVM options
  template:
    src: jvm.options.j2
    mode: 0644
    dest: /etc/elasticsearch/jvm.options
- name: Configure Elasticsearch Centos (ELK)
  become: true
  template:
    src: elasticsearch.yml.j2
    mode: 0644
    dest: /etc/elasticsearch/elasticsearch.yml
  environment:
    - ES_JAVA_OPTS: "-Djna.tmpdir=/var/log/elasticsearch"
  notify: restart Elasticsearch
  when: ansible_facts.pkg_mgr == "yum"
- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    mode: 0644
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart Elasticsearch Deb
  when: ansible_facts.pkg_mgr == "apt"