---
# - name: Update yum package manager repositories cache
#   become: true
#   yum:
#     update_cache: yes
- name: Install Elasticsearch
  become: true
  yum:
    name: "/tmp/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm"
    state: present
  notify: restart Elasticsearch
