---
- name: Install python
  apt:
    - python3-dev
    - python3-setuptools
    - python3-pip
    - python3-yaml
  state: present
- name: Install Elasticsearch
  apt:
    deb: "/tmp/elasticsearch-{{ elasticsearch_version }}-amd64.deb"
    state: present
  notify: restart Elasticsearch



  #- name: Update repositories cache and install "python" package
  #  become: true
  #  apt:
  #    name: python
  ##    update_cache: yes
  #- name: Install Java using Ansible
  #  become: true
  #  apt:
  #    name: "{{ packages }}"
  #    state: present
  #  vars:
  #    packages:
  #      - openjdk-11-jdk