---
- name: Update APT package manager repositories cache
  become: true
  yum:
    update_cache: yes
- name: install EPEL repo
  become: true
  yum:
    name: epel-release
    state: present
- name: install python
  become: true
  yum:
    name: python36
    state: present
- name: Install Java using Ansible
  become: yes
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - java-11-openjdk-devel.x86_64
- name: Install Elasticsearch
  yum:
    name: "/tmp/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm"
    state: present
  notify: restart Elasticsearch
