---
- name: Update repositories cache and install "python" package
  apt:
    update_cache: yes
# - name: vm.max_map_count
#   become: true
#   command: sysctl -w vm.max_map_count=262144
- name: Install Java using Ansible
  apt:
    name: openjdk-8-jdk
    state: present
- name: Install Elasticsearch
  apt:
    deb: "/tmp/elasticsearch-{{ elasticsearch_version }}-amd64.deb"
    state: present
  # notify: restart Elasticsearch Deb