---
dependency:
  name: galaxy
driver:
  name: podman
  managed: false
  login_cmd_template: sleep 5000000
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: instance-3
    image: docker.io/pycontribs/centos:7
    command: /sbin/init && sleep 5000000
    privileged: True
    published_ports:
      - 0.0.0.0:5005:5005/udp
      - 0.0.0.0:5005:5005/tcp
    pre_build_image: true
  - name: instance-4
    image: docker.io/pycontribs/ubuntu:latest
    command: sleep 5000000
    published_ports:
      - 0.0.0.0:5004:5004/udp
      - 0.0.0.0:5004:5004/tcp
    pre_build_image: true
    provisioner:
provisioner:
  name: ansible
verifier:
  name: ansible
