---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: instance-3
    image: docker.io/pycontribs/centos:7
    command: /sbin/init
    privileged: True
    pre_build_image: true
    networks:
      - elk-centos
  - name: instance-4
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
    networks:
      - elk-ubuntu
provisioner:
  name: ansible
  log: true
  options:
    vvv: true
    diff: true
verifier:
  name: ansible
