pipeline { 
    agent any 
    stages {
        stage('Structure of directories'){
            steps {
                sh 'tree \$PWD'
            }
        }
        stage('Molecule test'){
            steps {
                sh 'cd playbook/roles/elasticsearch-role'
                sh 'molecule test'
            }                        
        }                
    }

    post {
            sh 'Bye!'
    }
}