MOLECULE_TEST_DATE = ''

pipeline { 
    agent any 
    environment {
        MOLECULE_TEST_DATE = getDate()
    }
    stages {
        stage("Structure of directories"){
            sh 'tree \$PWD'
        }
        stage("Molecule test"){
            if (secret_check){
                sh 'cd playbook/roles/elasticsearch-role'
                sh 'molecule test'
            }
            else{
                echo 'need more action'
            }
            
        }
        
    }
}